### ISSUE TITLE
ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by HaroldStruwig** [happner/happn-3#159]
```
ReferenceError: callback is not defined
    at login (node_modules/happn-3/lib/services/security/service.js:295:29)
    at SecurityService.generateSession (node_modules/happn-3/lib/services/security/service.js:1183:3)
    at SecurityService.__loginOK (node_modules/happn-3/lib/services/security/service.js:1266:15)
    at matchPassword (node_modules/happn-3/lib/services/security/service.js:1405:21)
    at node_modules/happn-password-hash-and-salt/lib/hashsalt.js:115:5
    at PBKDF2.ondone (node_modules/happn-password-hash-and-salt/lib/hashsalt.js:76:7)
```

**Comment by JohanvdWest** [comment]
Also saw this in a single test run. This was the error code above it:

```
node_modules/happn-3/lib/services/security/service.js:298
      if (!attachedSession) return callback(new Error('session with id ' + sessionId + ' dropped while logging in'));
```
