### ISSUE TITLE
ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happn-3#163]
Got this message during a test-run. Only got it once.

Not sure if this is the same as #159 

```
node_modules/happn-3/lib/services/security/service.js:298
      if (!attachedSession) return callback(new Error('session with id ' + sessionId + ' dropped while logging in'));
                            ^

ReferenceError: callback is not defined
    at login (/home/johan/git/tunnel-proxy/node_modules/happn-3/lib/services/security/service.js:298:29)
    at SecurityService.generateSession (/home/johan/git/tunnel-proxy/node_modules/happn-3/lib/services/security/service.js:1186:3)
    at SecurityService.__loginOK (/home/johan/git/tunnel-proxy/node_modules/happn-3/lib/services/security/service.js:1269:15)
    at matchPassword (/home/johan/git/tunnel-proxy/node_modules/happn-3/lib/services/security/service.js:1422:21)
    at /home/johan/git/tunnel-proxy/node_modules/happn-password-hash-and-salt/lib/hashsalt.js:115:5
    at PBKDF2.ondone (/home/johan/git/tunnel-proxy/node_modules/happn-password-hash-and-salt/lib/hashsalt.js:76:7)
```

**Comment by JohanvdWest** [comment]
Closing as a duplicate of #159
