### ISSUE TITLE
HappnClient.on - TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by HaroldStruwig** [happner/happn-3#184]
**Required Info**
- **Priority:** C
- **Recommendation**: This causes the AE to crash. Recommend SB to fix this as part of [TR4127](https://github.com/orgs/FieldServer/projects/218)

**Notes**  
01/24/19-HS: Created and placed on ENG review after seeing this on our LTE test device.

Log:
```
2019-01-23 10:20:05.700 [FATAL] - 6050ms	(Mesh) uncaughtException (or set NO_EXIT_ON_UNCAUGHT) TypeError: Cannot read property 'status' of undefined
    at /node_js/app/node_modules/happn-3/lib/client.js:1634:24
    at Timeout._onTimeout (/node_js/app/node_modules/happn-3/lib/client.js:1100:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-01-23 10:20:05.707 [FATAL] - TypeError: Cannot read property 'status' of undefined
    at /node_js/app/node_modules/happn-3/lib/client.js:1634:24
    at Timeout._onTimeout (/node_js/app/node_modules/happn-3/lib/client.js:1100:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-01-23 10:20:05.801 [ INFO] - 101ms	(Mesh) exit 1
```

**Comment by southbite** [comment]
Ok, actually it does look like I can see how this can happen... Going to quickly implement a fix with a unit test.

**Comment by HaroldStruwig** [comment]
@southbite LTE test device is on of our ProtoAir units. Client and server is both on happner-2@9.2.3 with happn-3@8.2.4. Yes payload encryption was enabled.
