### ISSUE TITLE
error in logs - TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by HaroldStruwig** [happner/happn-3#196]
[TR4127](https://github.com/FieldServer/smc-project-board-issues/issues/185)

when it happens it seems to always be preceded by a user disconnecting but a user disconnecting does not always cause it

output:
```
2019-03-15 07:32:09.892 [ INFO] - 34301ms	(Happn) 'fieldpopClientUser' disconnected
2019-03-15 07:32:10.601 [ INFO] - 708ms	(Happn) 'fieldpopClientUser' connected
2019-03-15 07:32:21.678 [ INFO] - 11078ms	(Happn) '_ADMIN' disconnected
2019-03-15 07:32:22.462 [ INFO] - 784ms	(Happn) '_ADMIN' connected
2019-03-15 07:32:55.449 [ INFO] - 32988ms	(Happn) 'fieldpopClientUser' disconnected
2019-03-15 07:32:55.871 [ERROR] - 422ms	peppermoth_-ga (HappnServer) : TypeCannot read property 'undefined' of undefined, severity: 0 system error: ProtocolService, stack: TypeError: Cannot read property 'undefined' of undefined
    at CheckPoint._authorizeSession (/node_js/app/node_modules/happn-3/lib/services/security/checkpoint.js:293:32)
    at __checkRevocations (/node_js/app/node_modules/happn-3/lib/services/security/service.js:1485:21)
    at /node_js/app/node_modules/happn-3/lib/services/security/service.js:660:5
    at PersistedCache.__tryCallback (/node_js/app/node_modules/happn-3/lib/services/cache/cache_persist.js:382:17)
    at PersistedCache.get (/node_js/app/node_modules/happn-3/lib/services/cache/cache_persist.js:111:34)
    at PersistedCache.tryCatcher (/node_js/app/node_modules/happn-3/node_modules/bluebird/js/main/util.js:26:23)
    at PersistedCache.ret [as get] (eval at makeNodePromisifiedEval (/node_js/app/node_modules/happner-2/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at SecurityService.__checkRevocations (/node_js/app/node_modules/happn-3/lib/services/security/service.js:654:33)
    at SecurityService.authorize (/node_js/app/node_modules/happn-3/lib/services/security/service.js:1480:8)
    at SecurityService.processAuthorize (/node_js/app/node_modules/happn-3/lib/services/security/service.js:322:15)
    at ProtocolService.processInboundStack (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:67:32)
    at processLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:213:10)
    at /node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:473:16
    at next (/node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:5329:29)
    at /node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:969:16
    at HappnLayer.__inboundLayer (/node_js/app/node_modules/happner-2/lib/system/happn.js:282:5)
    at nextTask (/node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:5324:14)
    at next (/node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:5331:9)
    at /node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:969:16
    at /node_js/app/node_modules/happn-3/lib/services/protocol/service.js:202:7
    at nextTask (/node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_js/app/node_modules/happn-3/node_modules/async/dist/async.js:5334:5)
    at ProtocolService.processLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:201:9)
    at ProtocolService.processMessageInLayers (/node_js/app/node_modules/happn-3/lib/services/protocol/service.js:211:8)
    at SessionService.handleMessage (/node_js/app/node_modules/happn-3/lib/services/session/service.js:333:32)
    at SessionService.tryCatcher (/node_js/app/node_modules/happn-3/node_modules/bluebird/js/main/util.js:26:23)
    at SessionService.ret [as handleMessage] (eval at makeNodePromisifiedEval (/node_js/app/node_modules/happn-3/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:15:23)
    at Sparky.<anonymous> (/node_js/app/node_modules/happn-3/lib/services/session/service.js:396:11)
    at Sparky.emit (events.js:182:13)
    at Sparky.EventEmitter.emit (domain.js:441:20)
    at done (/node_js/app/node_modules/primus/spark.js:347:25)
    at transform (/node_js/app/node_modules/primus/spark.js:309:30)
    at Sparky.transforms (/node_js/app/node_modules/primus/spark.js:330:4)
    at decoding (/node_js/app/node_modules/primus/spark.js:215:13)
```

**Comment by southbite** [comment]
fixed in https://github.com/happner/happn-3/pull/199
