### ISSUE TITLE
unhandled error when remote client disconnects

### ISSUE THREAD

**Issue by JensEggers** [happner/happn-3#81]
```
Unhandled rejection Error: client is disconnected
    at HappnClient.__performDataRequest (/home/jens/git/fieldpop-user-mgr/node_modules/happn-3/lib/client.js:1104:25)
    at HappnClient.<anonymous> (/home/jens/git/fieldpop-user-mgr/node_modules/happn-3/lib/client.js:1185:10)
    at HappnClient.set (/home/jens/git/fieldpop-user-mgr/node_modules/happn-3/lib/client.js:52:33)
    at Object.securedMeshData.set (/home/jens/git/fieldpop-user-mgr/node_modules/happner-2/lib/system/component-instance.js:61:21)
    at Data.set (/home/jens/git/fieldpop-user-mgr/node_modules/happner-2/lib/modules/data/index.js:14:22)
    at value (/home/jens/git/fieldpop-user-mgr/node_modules/happner-2/lib/system/component-instance.js:443:39)
    at Immediate.<anonymous> (/home/jens/git/fieldpop-user-mgr/node_modules/happner-2/lib/system/shared/internals.js:184:19)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by JensEggers** [comment]
rather log an error

**Comment by southbite** [comment]
struggling to replicate this failure, when we chatted it was clear this happens when a client disconnects half way through an exchange operation, right? Looking at the stack this happens when a request is pushed over the local exchange - maybe when a remote client runs a method that calls another local components method or something. This issue doesn't happen when a websocket client disconnects half way through an exchange request. Any further input regarding frequency or circumstance would be much appreciated :)
